namespace: rkllama

resources:
  # Choose ONE: deployment.yml (single node) OR daemonset.yml (multi-node cluster)
  - ./deployment.yml
  # - ./daemonset.yml
  - ./ingress.yml
  - ./pv.yml
  - ./service.yml

images:
  - name: ghcr.io/rsjames-ttrpg/rkllama
    newTag: 1ddfb1f
