namespace: rkllama

resources:
  - ./deployment.yml
  - ./ingress.yml
  - ./pv.yml
  - ./service.yml

images:
  - name: ghcr.io/rsjames-ttrpg/rkllama
    newTag: latest  # Change to specific version e.g. v0.1.0
